### ISSUE TITLE
The project is basically successful.

### ISSUE THREAD

**Issue by Jewelleryliu** [TeksuSiK/e46-cluster-simhub#2]
Thank you again for your circuit diagram and code. I basically realized the work of the indicator light by consulting the chip manual and changing part of the code. But there are some imperfections in it. For example, the near-light is not the same byte as other indicator lights. I need to continue learning and change the code.

https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/4997d8b0-6dc7-455f-8691-82f1723429ff

**Comment by TeksuSiK** [comment]
I'm very glad you made it. I'm sorry I haven't had much time to reply to you, but I've been very busy lately. Could you tell me what exactly needed to be changed to make it work? I'm willing to improve the code if you give me some tips.

**Comment by Jewelleryliu** [comment]
I'm glad to make friends with you, although you haven't replied to me for a while. In the first picture, I changed some code, but after the modification, the time did not take effect. I tried to add some delays, but it didn't work. The test frameIndicator [7] is beam low, but I tried to change some code, and it can't be like a real car. Can you help me? Looking forward to your reply. By the way, 2021a needs to be changed to a master node according to the chip manual.
![IMG_2311](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/97149a1e-3971-417a-865d-b93c7d5e0b08)
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/66021e15-b7df-4e57-8089-2634ec66c528)

https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/9686cb39-bdf9-4ab1-9018-c246ea05e095

**Comment by Jewelleryliu** [comment]
I'm glad to make friends with you, although you haven't replied to me for a while. In the first picture, I changed some code, but after the modification, the time did not take effect. I tried to add some delays, but it didn't work. The test frameIndicator [7] is beam low, but I tried to change some code, and it can't be like a real car. Can you help me? Looking forward to your reply. By the way, 2021a needs to be changed to a master node according to the chip manual.
![IMG_2311](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/97149a1e-3971-417a-865d-b93c7d5e0b08)
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/66021e15-b7df-4e57-8089-2634ec66c528)

https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/9686cb39-bdf9-4ab1-9018-c246ea05e095

**Comment by Jewelleryliu** [comment]
Time is OK

**Comment by TeksuSiK** [comment]
Hi. I temporarily removed the frame responsible for setting the time because it was actually causing problems. The IbusTrx library has some problems sending messages from the buffer if there is more than one message there. I'm attaching a video of showing that everything is working now. Additionally, I made an update that adds traction control and braking system failure fields. In ETS2, I attributed the brake system failures to the brake air pressure warning. I encourage you to clone the repository fresh, upload a new code and of course update the custom protocol in SimHub.

https://github.com/TeksuSiK/e46-cluster-simhub/assets/32488713/16b64988-ac12-4b2a-9313-d84aae1c60f3

**Comment by Jewelleryliu** [comment]
How about the beam low？

**Comment by TeksuSiK** [comment]
Old BMWs did not have any low beam indicator light

**Comment by Jewelleryliu** [comment]
![IMG_2332](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/2a1aaba9-008b-42cf-adba-57fd0a20af4e) frameIndicators [7]

**Comment by TeksuSiK** [comment]
This is not a low beam indicator. This is the Check Control screen which shows problems with bulbs if any are burned out. However, I can add support for this screen to the code and then, by changing the custom protocol, it will be possible to use it as a low beam indicator.

**Comment by Jewelleryliu** [comment]
Thank you. Let me know if you modify the code.

**Comment by TeksuSiK** [comment]
I have updated the code to control this display. You can install the latest version and adapt the custom protocol to display low beam headlights. I didn't do it in the main branch file, but I prepared one for you

```js
var ignition = Number($prop('GameRawData.TruckValues.CurrentValues.ElectricEnabled'));

var lights_side = Number($prop('GameRawData.TruckValues.CurrentValues.LightsValues.Parking'));
var lights_dip = Number($prop('GameRawData.TruckValues.CurrentValues.LightsValues.BeamLow'));
var lights_main = Number($prop('GameRawData.TruckValues.CurrentValues.LightsValues.BeamHigh'));
var lights_front_fog = Number($prop('GameRawData.TruckValues.CurrentValues.LightsValues.Beacon'));
var lights_rear_fog = 0;

var lights_indicators;
if ($prop('TruckSimulatorPlugin.Lights.HazardWarningOn')) {
    lights_indicators = 3;
} else if ($prop('GameRawData.TruckValues.CurrentValues.LightsValues.BlinkerLeftActive')) {
    lights_indicators = 1;
} else if ($prop('GameRawData.TruckValues.CurrentValues.LightsValues.BlinkerRightActive')) {
    lights_indicators = 2;
} else {
    lights_indicators = 0;
}

var lights_ccm_display = 0;
var lights_ccm_low_left = Number($prop('GameRawData.TruckValues.CurrentValues.LightsValues.BeamLow'));
var lights_ccm_low_right = Number($prop('GameRawData.TruckValues.CurrentValues.LightsValues.BeamLow'));
var lights_ccm_brake_left = 0;
var lights_ccm_brake_right = 0;

var rpm = Math.round($prop('Rpms'));
var speed = Math.round($prop('SpeedKmh'));
var fuel = 0;

var engine_temperature = Math.round($prop('WaterTemperature'));

var abs = 0;
var traction_control = 0;
var brake_fault = Number($prop('GameRawData.TruckValues.CurrentValues.DashboardValues.WarningValues.AirPressure'));;
var oil_pressure = Number($prop('GameRawData.TruckValues.CurrentValues.DashboardValues.WarningValues.OilPressure'));
var charging = Number($prop('GameRawData.TruckValues.CurrentValues.DashboardValues.WarningValues.BatteryVoltage'));
var handbrake = Number($prop('GameRawData.TruckValues.CurrentValues.MotorValues.BrakeValues.ParkingBrake'));
var check_engine = Number($prop('TruckSimulatorPlugin.Damage.WearWarning'));
var cruise_control = Number($prop('GameRawData.TruckValues.CurrentValues.DashboardValues.CruiseControl'));
var dde = Number($prop('TruckSimulatorPlugin.Engine.Starting'));
var coolant_overheating = Number($prop('GameRawData.TruckValues.CurrentValues.DashboardValues.WarningValues.WaterTemperature'));

return `SH;${ignition};${lights_side};${lights_dip};${lights_main};${lights_front_fog};${lights_rear_fog};${lights_indicators};${lights_ccm_display};${lights_ccm_low_left};${lights_ccm_low_right};${lights_ccm_brake_left};${lights_ccm_brake_right};${rpm};${speed};${fuel};${engine_temperature};${abs};${traction_control};${brake_fault};${oil_pressure};${charging};${handbrake};${check_engine};${cruise_control};${dde};${coolant_overheating};\n`
```
