### ISSUE TITLE
The indicator light has taken effect.

### ISSUE THREAD

**Issue by Jewelleryliu** [TeksuSiK/e46-cluster-simhub#3]
You did a great job, thank you! I have added the time code, and it has taken effect,.The fuel meter did not take effect by changing the code, which may be related to the year of the car. I will consider the code of the oil meter later.

**Comment by TeksuSiK** [comment]
The fuel meter is controlled by the resistance of the float, and setting it via digital potentiometers (there are two sensors) is not very precise. Additionally, the update time itself is quite slow, so I don't see the point in working on it. I have 400 Ohm resistors connected between the sensor pins. I will try to restore the time display when I have some free time.

**Comment by Jewelleryliu** [comment]
By the way, ets2's JavaScript has no return value for some items. I took a general look, and it seemed that there was no return value for the danger alarm light, engine failure light and EML. For the fuel meter, I can refer to the relevant projects in GitHub. I will test it when I have time. It seems to be the iic protocol and needs an operational amplifier.

**Comment by Jewelleryliu** [comment]
Uploading 36c766fb30b2d57181dc2b0012157f.mp4…

**Comment by Jewelleryliu** [comment]
https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/4aad518c-496c-4ff5-8071-15aaf88e9d03

**Comment by TeksuSiK** [comment]
If you do not have any action on the check engine and EML indicators (and in diesel DDE), install the [TruckSimulatorPlugin](https://github.com/sjdawson/TruckSimulatorPlugin) to SimHub. In the default protocol, I assigned the EML indicator to starting the engine, and the check engine indicator is on if the truck is damaged. By the way, interesting use of the rear fog indicator as a reversing light.

**Comment by Jewelleryliu** [comment]
Sorry, could you spare some time to tell me how to install TruckSimulatorPlugin.

**Comment by Jewelleryliu** [comment]
Hello！There is no TruckSimulatorPlugin.Engine.Starting.Besides, all functions are in effect！I have installed the latest plugin.
