### ISSUE TITLE
Gear box

### ISSUE THREAD

**Issue by Jewelleryliu** [TeksuSiK/e46-cluster-simhub#5]
https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/273ca67d-ad57-443d-8ad0-483604ef8f61

**Comment by Jewelleryliu** [comment]
Uploading IMG_2351.mov…

**Comment by TeksuSiK** [comment]
If you want, you can make a pull request. I would love to add this feature to the main branch. Unfortunately, I do not have a meter with this display.
